#! /bin/bash
# Get a vm.  Argument specifies virtual machine desciption,
# e.g., centos-7-x86_64

cmd="curl -H X-AUTH-TOKEN:$(gt) -d --url vmpooler.delivery.puppetlabs.net/vm/$1"
echo $cmd
$cmd
echo 
