#! /usr/bin/perl -w
# List the names of the VMs I have checked out.

my $a = `curl -X GET --url vmpooler/token/\`gt\` 2>/dev/null`;
my @myvms = split(/\"running\": \[/, $a);
if (scalar @myvms < 2) {
  exit (0);
} 
@myvms = split(/,/, (split(/]/, $myvms[1]))[0]);
foreach my $vm (@myvms) {
  $vm = (split(/\"/, $vm))[1];
  print("$vm\n");
}
exit (0)
